# Generated by Django 5.1.1 on 2024-10-01 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0002_rename_name_contact_name_rename_phone_contact_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactMessage',
        ),
    ]
