# Generated by Django 5.1.1 on 2024-10-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_app', '0003_rename_contact_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Section',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('about_title', models.CharField(max_length=50)),
                ('Short_content', models.TextField()),
                ('heading_line', models.CharField(max_length=50)),
                ('content1', models.TextField()),
                ('content2', models.TextField()),
            ],
            options={
                'verbose_name': 'About TEQPEERS TECHNOLOGY',
                'verbose_name_plural': 'About TEQPEERS TECHNOLOGIES',
            },
        ),
    ]
