# Generated by Django 5.1.1 on 2024-10-02 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('tech_Notes_pdf', models.FileField(upload_to='Course_documents/Notes')),
                ('tech_Cheatsheet_pdf', models.FileField(upload_to='Course_documents/Cheatsheet')),
                ('Card_image', models.ImageField(blank=True, upload_to='blog/images')),
                ('tech_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course_app.card_list', verbose_name='Technology Name')),
            ],
        ),
    ]
