# Generated by Django 5.1.1 on 2024-10-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectNotes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': ' Course SourceCode', 'verbose_name_plural': 'Course SourceCodes'},
        ),
    ]
