# Generated by Django 5.1.1 on 2024-10-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectNotes_app', '0002_alter_notes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='Card_image',
            field=models.ImageField(blank=True, upload_to='Course_documents/images'),
        ),
    ]
