# Generated by Django 5.1.1 on 2024-10-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0001_initial'),
        ('ProjectNotes_app', '0003_alter_notes_card_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Notes_Section',
        ),
    ]
