# Generated by Django 5.1.1 on 2024-10-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectNotes_app', '0005_project_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_section',
            old_name='Project_Code',
            new_name='Project_Code_1',
        ),
        migrations.RenameField(
            model_name='project_section',
            old_name='headline_4',
            new_name='Project_Code_2',
        ),
        migrations.RenameField(
            model_name='project_section',
            old_name='Project_content',
            new_name='Project_content_1',
        ),
        migrations.AddField(
            model_name='project_section',
            name='Project_Code_3',
            field=models.CharField(default=None, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='project_section',
            name='Project_content_2',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='project_section',
            name='Project_content_3',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project_section',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Category of Projects'),
        ),
    ]
