# Generated by Django 5.1.1 on 2024-10-01 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_list',
            fields=[
                ('cad_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='card_images/')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('top_id', models.AutoField(primary_key=True, serialize=False)),
                ('Chapter_title', models.CharField(max_length=200)),
                ('title1', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
                ('title3', models.CharField(max_length=200)),
                ('title4', models.CharField(max_length=200)),
                ('title5', models.CharField(max_length=200)),
                ('title6', models.CharField(max_length=200)),
                ('card_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Course_app.card_list')),
            ],
        ),
        migrations.CreateModel(
            name='TopicDetail',
            fields=[
                ('top_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='card_images/')),
                ('t1', models.CharField(max_length=50)),
                ('content_t1', models.TextField()),
                ('code_t1', models.TextField()),
                ('t2', models.CharField(max_length=50)),
                ('content_t2', models.TextField()),
                ('code_t2', models.TextField()),
                ('t3', models.CharField(max_length=50)),
                ('content_t3', models.TextField()),
                ('code_t3', models.TextField()),
                ('t4', models.CharField(max_length=50)),
                ('content_t4', models.TextField()),
                ('code_t4', models.TextField()),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='Course_app.topic')),
            ],
        ),
    ]
